reputation_clear_post_controller:
    pattern: /reputation/clear/post/{post_id}
    defaults: { _controller: pico.reputation.action.controller:clear_post }
    requirements:
        post_id: \d+

reputation_clear_user_controller:
    pattern: /reputation/clear/user/{uid}
    defaults: { _controller: pico.reputation.action.controller:clear_user }
    requirements:
        uid: \d+

reputation_delete_controller:
    pattern: /reputation/delete/{rid}
    defaults: { _controller: pico.reputation.action.controller:delete }
    requirements:
        rid: \d+

reputation_details_controller:
    pattern: /reputation/{uid}/{sort_key}/{sort_dir}/{page}
    defaults: { _controller: pico.reputation.details.controller:details, sort_key: id, sort_dir: dsc, page: 1 }
    requirements:
        uid: \d+
        sort_key: id|username|time|point|action
        sort_dir: asc|dsc

reputation_post_details_controller:
    pattern: /reputation/details/post/{post_id}/{sort_key}/{sort_dir}
    defaults: { _controller: pico.reputation.details.controller:postdetails, sort_key: id, sort_dir: dsc }
    requirements:
        post_id: \d+
        sort_key: id|username|time|point
        sort_dir: asc|dsc

reputation_post_rating_controller:
    pattern: /reputation/rate/post/{mode}/{post_id}
    defaults: { _controller: pico.reputation.rating.controller:post }
    requirements:
        mode: positive|negative
        post_id: \d+

reputation_user_details_controller:
    pattern: /reputation/details/user/{uid}/{sort_key}/{sort_dir}
    defaults: { _controller: pico.reputation.details.controller:userdetails, sort_key: id, sort_dir: dsc }
    requirements:
        uid: \d+
        sort_key: id|username|time|point|action
        sort_dir: asc|dsc

reputation_user_rating_controller:
    pattern: /reputation/rate/user/{uid}
    defaults: { _controller: pico.reputation.rating.controller:user }
    requirements:
        uid: \d+
